# Generated by Django 2.0.6 on 2018-06-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(choices=[(0, 'NR - Not Rated'), (1, 'G - Genral Audiences'), (2, 'PG - Parental Guidance Suggested'), (3, 'R - Restricted')], default=0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
